### ISSUE TITLE
Adding a META.json file to this distribution

### ISSUE THREAD

**Issue by oalders** [braintree/braintree_perl#14]
If this distribution had a META.json file with the path to the repository inside it, it would be much easier to find the Github repository.  It's quite easy to do, as explained here: http://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions  I can also send a pull request, if that's easier.

If this is done, MetaCPAN.org can link directly to this repository from the module's documentation.

**Comment by openbl** [comment]
@oalders, while our Perl library is deprecated we're happy to review a PR for this.

**Comment by pblesi** [comment]
I am closing this issue as we are not actively developing our Perl library at this time.
