### ISSUE TITLE
Make deprecation more obvious

### ISSUE THREAD

**Issue by oalders** [braintree/braintree_perl#15]
I see that this module has been deprecated.  It's noted in README.md but _not_ in README, which is unfortunate.  It would be helpful to add some documentation to lib/Net/Braintree.pm noting that the module is deprecated, as that is where most people would expect to find this.  Adding it to the README proper would be good too.

**Comment by pblesi** [comment]
@oalders Thank you for pointing this out and sorry for not getting back to you sooner. I have updated both the `README` and `lib/Net/Braintree.pm` to include notices that the library is deprecated. We will be releasing an updated version with these changes shortly.

Cheers!

**Comment by oalders** [comment]
@pblesi sounds good. Thanks for taking care of this. 👍
