### ISSUE TITLE
'errors' and 'credit_card_verification' methods sometimes die

### ISSUE THREAD

**Issue by neatonk** [braintree/braintree_perl#7]
```perl
my $result = <some api call that returns a result>;
$result->is_success;
#1
$result->errors;
#Single parameters to new() must be a HASH ref at [...]
```

This can be easily avoid by not calling the `errors` or `credit_card_verification` methods when `is_success` is true, but it would be better if these methods returned `undef` or threw a more meaningful error instead.

**Comment by pblesi** [comment]
Closing this issue because our Perl client library is deprecated and not in active develop.
